import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth' //Server side session fetcher
import { SessionProvider } from 'next-auth/react'
import { Inter } from 'next/font/google'
import NavMenu from './components/NavMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // awaiting getServerSession() as it is a promise
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Now the session is available to any client component through the SessionProvider Context */}
        <SessionProvider session={session}>
          <main className="mx-auto max-w-5xl text-2xl flex gap-2">
            <NavMenu />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
